### ISSUE TITLE
Future Ownership

### ISSUE THREAD

**Issue by GregoryDosh** [J3n50m4t/Home-Assistant-DreamScreen-Service#33]
Just as an awareness thing, I've no longer got a Dreamscreen so I'm not able to continue maintaining this. I know that @J3n50m4t was doing a lot of work on this and keeping it relevant. If someone wants to take ownership and move the repo into their own space I'm more than happy to facilitate that. Otherwise I don't believe I'll be active in this project any longer.

**Comment by J3n50m4t** [comment]
Hey Gregory, 
I'm not a python developer in the first place, but I will keep it up to date. Big Feature Requests may be a bit difficult for me, but I always try my best.
Feel free to transfer it to me. I will publish updates, as I still love my dreamscreen and i love Homeassistant.
