### ISSUE TITLE
Rediscover Dreamscreen after power outage of dreamscreen

### ISSUE THREAD

**Issue by eddetollenaer** [J3n50m4t/Home-Assistant-DreamScreen-Service#34]
Hi,
My dreamscreen and all other TV equipment is connected to a single smart plug which turns everything (including the Dreamscreen) off when nobody is watching television. Als, my Home Assistant is rebooting every night. After that, the dreamscreen is not detected anymore and cannot be found in HA anymore. Powering on the Dreamscreen does not fix this. I have to power  on the dreamscreen and then restart HA to see the device again. Is there a way so that HA will automatically redetect the dreamscreen again when it gets powered on?

**Comment by J3n50m4t** [comment]
Looks like the same as #11 
Man this issue is almost a year old. I definitly will try to fix this, but I can't give an ETA. Sorry
