### ISSUE TITLE
Hassio Updates breaks Intergrations

### ISSUE THREAD

**Issue by nixx3d** [J3n50m4t/Home-Assistant-DreamScreen-Service#41]
![image](https://user-images.githubusercontent.com/7212781/105025133-369a5e00-5a4d-11eb-9ca3-854a48abeb0d.png)
Hi there, thanks for this component!

Unfortunately it seems to have broken after the latest Hassio (security) update. (0.117.6)

Any chance you can update this component?

thanks!

**Comment by XRyu** [comment]
Hmm, not sure if Hassio might make any incompatibilities - but here on
plain Home Assistant on Docker (so no Hassio) its running fine - on Version
2021.1.4

Did you try restarting? I remember i once had a problem too, after many
tries it "just" worked again after that - and maybe adding the ip to
configuration.

Am Di., 19. Jan. 2021 um 11:57 Uhr schrieb nixx3d <notifications@github.com

**Comment by J3n50m4t** [comment]
Sadly mine broke.
I only can work with your logs.

Could you add the startup Logs?
