### ISSUE TITLE
Entity ID Issue

### ISSUE THREAD

**Issue by zosobao5150** [J3n50m4t/Home-Assistant-DreamScreen-Service#42]
Hi, I have added this service to my home assistant several times now, but I keep getting an issue where I can actually put the device on the dashboard, or even control it.  I keep getting the following error, but am unsure where I need to place an actual fix for it. Any help would be appreciated.

This entity ("dreamscreen.dream_screen") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.

**Comment by J3n50m4t** [comment]
Could you provide some infos, why you closed this, so someone who runs into the same problem can resolve it easily?

**Comment by zosobao5150** [comment]
Hi. Sorry. I ended up watching  outube video(2-pars) on how to set up the dreamscreen in home assistant. There was a lot of special things needed, including modifying the configuration yaml file. No way I could have implemented it without.

**Comment by J3n50m4t** [comment]
Whats missing in [Readme.mein](https://github.com/J3n50m4t/Home-Assistant-DreamScreen-Service#configuration)
