### ISSUE TITLE
Needs a version key for Home Assistant By v2021.6

### ISSUE THREAD

**Issue by zanix** [J3n50m4t/Home-Assistant-DreamScreen-Service#43]
Home assistant is requiring a version key in the `manifest.json` file of all custom components by version ​2021.6.

> WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'dreamscreen'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'dreamscreen'

To keep Home assistant quiet I just added the date of the last git commit
```json
{
    "domain": "dreamscreen",
    "name": "DreamScreen",
    "documentation": "https://github.com/GregoryDosh/Home-Assistant-DreamScreen-Service",
    "dependencies": [],
    "codeowners": ["https://github.com/GregoryDosh"],
    "requirements": ["PyDreamScreen>=0.0.14"],
    "version": "2020.8.5"
  }
```

**Comment by J3n50m4t** [comment]
Feel free to Create a pr

**Comment by zanix** [comment]
Done!
